### ISSUE TITLE
Hide "One Change" column

### ISSUE THREAD

**Issue by zimage** [mylaaan/FtHoF-Planner-v4#2]
As a beginner player who can't change seasons, it's unnecessary to see the "One Change" column. I'd love to be able to click a checkbox to hide that column.

**Comment by mylaaan** [comment]
Didn't see the need as it is simple to look over it and the planner is probably used mostly by advanced players. But I did a try-out and it came out looking clean enough that I decided to make it permanent. So, give it a hard reload and enjoy.
