### ISSUE TITLE
Support for new v 2.048 dragon aura Supreme Intellect

### ISSUE THREAD

**Issue by captaindun** [mylaaan/FtHoF-Planner-v4#4]
New building Cortex Bakers and associated dragon aura Supreme Intellect were introduced in Cookie Clicker version 2.048.  When this aura is active, Grimoire spells fail 10% more.  Orteil must have added a conditional branch to his spell fail logic.  There should be an extra checkbox in the FtHoF planner to enable the user to specify when Supreme Intellect is active, and for the different results to then be shown in the results table.

I don't know what happens when both Supreme Intellect and Reality Bending are active; it would be nice if you could handle that too.

Thanks for a great tool and thanks in advance if you can accommodate this change!

**Comment by mylaaan** [comment]
Oky I wanted to say immediately that this is nothing to worry about as I already tested it with a 100 spells and the positive/negative outcome does not deviate from the planner. I now actually did another 70 spells (it already became a little silly) where I imported my save code and then I activated Supreme Intellect. Still no change.
But maybe also for my own sake I still made the button. As many probably still won't read the manual that it doesn't matter or even if I would tag it with the current version on top. A placebo for now will make do. If CC ever gets updated that this feature actually changes things someone will implement it.
The current live version of the planner already has the button, so I will close this support ticket
